linter:
  rules:
    library_names: true
    avoid_empty_else: true
    unawaited_futures: false
analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
  exclude:
    - lib/generated_plugin_registrant.dart
    - test/**_test.dart
enable-experiment:
  - extension-methods
